# Generated by Django 2.2 on 2020-01-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='issueregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialno', models.TextField()),
                ('nomenclature', models.TextField()),
                ('quantityheld', models.TextField()),
                ('issueqty', models.TextField()),
                ('subdepot', models.TextField()),
                ('unit', models.TextField()),
            ],
        ),
    ]
