# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-25 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyapp', '0003_auto_20200124_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='materialno',
            field=models.TextField(unique=True),
        ),
    ]
