# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-25 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('armyapp', '0004_auto_20200124_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueregister',
            name='currentdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
