# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyapp', '0006_auto_20200124_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='loadchart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.TextField()),
                ('totalload', models.IntegerField()),
                ('expdate', models.DateField()),
                ('sd1', models.IntegerField()),
                ('d1', models.DateField()),
                ('sd2', models.IntegerField()),
                ('d2', models.DateField()),
                ('sd3', models.IntegerField()),
                ('d3', models.DateField()),
                ('sd4', models.IntegerField()),
                ('d4', models.DateField()),
            ],
        ),
    ]
