# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-25 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyapp', '0007_loadchart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadchart',
            name='d1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loadchart',
            name='d2',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loadchart',
            name='d3',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loadchart',
            name='d4',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loadchart',
            name='expdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loadchart',
            name='sd1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loadchart',
            name='sd2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loadchart',
            name='sd3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loadchart',
            name='sd4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loadchart',
            name='totalload',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loadchart',
            name='unit',
            field=models.TextField(null=True),
        ),
    ]
