# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-06 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyapp', '0010_auto_20200205_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='materialno',
            field=models.CharField(error_messages={'unique': 'This email has already been registered.'}, max_length=50, unique=True),
        ),
    ]
